language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=elephantsqp

before_script:
  - psql -c 'CREATE database teamworktest;' -U postgres
  - psql -c 'DROP database teamworktest;' -U postgres
  - psql -c 'CREATE database teamworktest;' -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'root';" -U postgres
  - npm run datadump

script:
  - npm run test

after_success:
  - npm run coverage