language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=travis

  addons:
  postgresql: "12"

before_script:
  - psql -c 'CREATE database teamworktest;' -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'root';" -U postgres
  - psql -c migrations/teamwork.sql

script:
  - npm run test

after_success:
  - npm run coverage
